language: cpp
compiler:
- g++
os:
- linux
git:
  submodules: true
env:
  - DO_ENABLE_SH4_MMU=OFF DO_ENABLE_SH4_ICACHE=OFF DO_ENABLE_SH4_OCACHE=OFF
  - DO_ENABLE_SH4_MMU=OFF DO_ENABLE_SH4_ICACHE=OFF DO_ENABLE_SH4_OCACHE=ON
  - DO_ENABLE_SH4_MMU=OFF DO_ENABLE_SH4_ICACHE=ON DO_ENABLE_SH4_OCACHE=OFF
  - DO_ENABLE_SH4_MMU=OFF DO_ENABLE_SH4_ICACHE=ON DO_ENABLE_SH4_OCACHE=ON
  - DO_ENABLE_SH4_MMU=ON DO_ENABLE_SH4_ICACHE=OFF DO_ENABLE_SH4_OCACHE=OFF
  - DO_ENABLE_SH4_MMU=ON DO_ENABLE_SH4_ICACHE=OFF DO_ENABLE_SH4_OCACHE=ON
  - DO_ENABLE_SH4_MMU=ON DO_ENABLE_SH4_ICACHE=ON DO_ENABLE_SH4_OCACHE=OFF
  - DO_ENABLE_SH4_MMU=ON DO_ENABLE_SH4_ICACHE=ON DO_ENABLE_SH4_OCACHE=ON
script:
  mkdir build ;
  cd build ;
  cmake -DENABLE_SH4_MMU=$DO_ENABLE_SH4_MMU \
        -DENABLE_SH4_ICACHE=$DO_ENABLE_SH4_ICACHE \
        -DENABLE_SH4_OCACHE=$DO_ENABLE_SH4_OCACHE .. ;
  make ;
  ./sh4asm_test && ./sh4_test && ./sh4inst_test
