name: Linux CI build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        mmu_enabled: [ Off, On ]
        invariants : [ Off, On ]

    steps:
    - uses: actions/checkout@v1
    - uses: textbook/git-checkout-submodule-action@2.0.0
    - uses: lpenz/ghaction-cmake@0121873f072dde7b17c6ed5e21bec976bfce025a
      with:
         dependencies: libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libgl-dev libglu-dev libxi-dev
         cmakeflags: -DENABLE_MMU=${{ matrix.mmu_enabled }} -DINVARIANTS=${{ matrix.invariants }}
