name: Linux CI build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: snickerbockers/submodules-init@v1
    - uses: lpenz/ghaction-cmake@v0.1
      with:
         dependencies: libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libgl-dev libglu-dev libxi-dev
