name: windows build

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: snickerbockers/submodules-init@v3
    - uses: snickerbockers/cmake-configure@b830b1af86c3491dc0a604072e41f6701a429ef7
      with:
        generator: 'MinGW Makefiles'
