name: windows build

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: snickerbockers/submodules-init@v4
    - uses: snickerbockers/cmake-configure@3625b26787079e132fd8661c292086d4a5df05a4
      with:
        generator: 'MinGW Makefiles'
    - uses: snickerbockers/run-mingw32-make@bbd004aa8f33a89e80c9bbcb726b42aeddb0a001
